// flasher_asmi_parallel2_top_0.v

// This file was auto-generated from altera_asmi_parallel2_top_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module flasher_asmi_parallel2_top_0 #(
		parameter DEVICE_FAMILY = "Cyclone IV E"
	) (
		input  wire        clk_clk,               //     clk.clk
		input  wire        reset_reset_n,         //   reset.reset_n
		input  wire [5:0]  avl_csr_address,       // avl_csr.address
		input  wire        avl_csr_read,          //        .read
		output wire [31:0] avl_csr_readdata,      //        .readdata
		input  wire        avl_csr_write,         //        .write
		input  wire [31:0] avl_csr_writedata,     //        .writedata
		output wire        avl_csr_waitrequest,   //        .waitrequest
		output wire        avl_csr_readdatavalid, //        .readdatavalid
		input  wire        avl_mem_write,         // avl_mem.write
		input  wire [6:0]  avl_mem_burstcount,    //        .burstcount
		output wire        avl_mem_waitrequest,   //        .waitrequest
		input  wire        avl_mem_read,          //        .read
		input  wire [18:0] avl_mem_address,       //        .address
		input  wire [31:0] avl_mem_writedata,     //        .writedata
		output wire [31:0] avl_mem_readdata,      //        .readdata
		output wire        avl_mem_readdatavalid, //        .readdatavalid
		input  wire [3:0]  avl_mem_byteenable     //        .byteenable
	);

	wire  [31:0] asmi2_addr_adaption_asmi_mem_readdata;      // asmi2_core:avl_mem_readdata -> asmi2_addr_adaption:asmi_mem_rddata
	wire         asmi2_addr_adaption_asmi_mem_waitrequest;   // asmi2_core:avl_mem_waitrequest -> asmi2_addr_adaption:asmi_mem_waitrequest
	wire  [31:0] asmi2_addr_adaption_asmi_mem_address;       // asmi2_addr_adaption:asmi_mem_addr -> asmi2_core:avl_mem_address
	wire         asmi2_addr_adaption_asmi_mem_read;          // asmi2_addr_adaption:asmi_mem_read -> asmi2_core:avl_mem_read
	wire   [3:0] asmi2_addr_adaption_asmi_mem_byteenable;    // asmi2_addr_adaption:asmi_mem_byteenable -> asmi2_core:avl_mem_byteenable
	wire         asmi2_addr_adaption_asmi_mem_readdatavalid; // asmi2_core:avl_mem_readdatavalid -> asmi2_addr_adaption:asmi_mem_rddata_valid
	wire         asmi2_addr_adaption_asmi_mem_write;         // asmi2_addr_adaption:asmi_mem_write -> asmi2_core:avl_mem_write
	wire  [31:0] asmi2_addr_adaption_asmi_mem_writedata;     // asmi2_addr_adaption:asmi_mem_wrdata -> asmi2_core:avl_mem_writedata
	wire   [6:0] asmi2_addr_adaption_asmi_mem_burstcount;    // asmi2_addr_adaption:asmi_mem_burstcount -> asmi2_core:avl_mem_burstcount
	wire         rst_controller_reset_out_reset;             // rst_controller:reset_out -> asmi2_addr_adaption:reset

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (DEVICE_FAMILY != "Cyclone IV E")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					device_family_check ( .error(1'b1) );
		end
	endgenerate

	flasher_asmi_parallel2_top_0_asmi2_core asmi2_core (
		.avl_csr_address       (avl_csr_address),                            // avl_csr.address
		.avl_csr_read          (avl_csr_read),                               //        .read
		.avl_csr_readdata      (avl_csr_readdata),                           //        .readdata
		.avl_csr_write         (avl_csr_write),                              //        .write
		.avl_csr_writedata     (avl_csr_writedata),                          //        .writedata
		.avl_csr_waitrequest   (avl_csr_waitrequest),                        //        .waitrequest
		.avl_csr_readdatavalid (avl_csr_readdatavalid),                      //        .readdatavalid
		.avl_mem_address       (asmi2_addr_adaption_asmi_mem_address),       // avl_mem.address
		.avl_mem_read          (asmi2_addr_adaption_asmi_mem_read),          //        .read
		.avl_mem_readdata      (asmi2_addr_adaption_asmi_mem_readdata),      //        .readdata
		.avl_mem_write         (asmi2_addr_adaption_asmi_mem_write),         //        .write
		.avl_mem_writedata     (asmi2_addr_adaption_asmi_mem_writedata),     //        .writedata
		.avl_mem_byteenable    (asmi2_addr_adaption_asmi_mem_byteenable),    //        .byteenable
		.avl_mem_burstcount    (asmi2_addr_adaption_asmi_mem_burstcount),    //        .burstcount
		.avl_mem_waitrequest   (asmi2_addr_adaption_asmi_mem_waitrequest),   //        .waitrequest
		.avl_mem_readdatavalid (asmi2_addr_adaption_asmi_mem_readdatavalid), //        .readdatavalid
		.clk_clk               (clk_clk),                                    //     clk.clk
		.reset_reset           (~reset_reset_n)                              //   reset.reset
	);

	avl_mem_addr_adaption #(
		.ADDR_WIDTH      (19),
		.ASMI_ADDR_WIDTH (32)
	) asmi2_addr_adaption (
		.clk                   (clk_clk),                                    // clock_sink.clk
		.reset                 (rst_controller_reset_out_reset),             //      reset.reset
		.avl_mem_write         (avl_mem_write),                              //    avl_mem.write
		.avl_mem_burstcount    (avl_mem_burstcount),                         //           .burstcount
		.avl_mem_waitrequest   (avl_mem_waitrequest),                        //           .waitrequest
		.avl_mem_read          (avl_mem_read),                               //           .read
		.avl_mem_addr          (avl_mem_address),                            //           .address
		.avl_mem_wrdata        (avl_mem_writedata),                          //           .writedata
		.avl_mem_rddata        (avl_mem_readdata),                           //           .readdata
		.avl_mem_rddata_valid  (avl_mem_readdatavalid),                      //           .readdatavalid
		.avl_mem_byteenable    (avl_mem_byteenable),                         //           .byteenable
		.asmi_mem_addr         (asmi2_addr_adaption_asmi_mem_address),       //   asmi_mem.address
		.asmi_mem_read         (asmi2_addr_adaption_asmi_mem_read),          //           .read
		.asmi_mem_rddata       (asmi2_addr_adaption_asmi_mem_readdata),      //           .readdata
		.asmi_mem_write        (asmi2_addr_adaption_asmi_mem_write),         //           .write
		.asmi_mem_wrdata       (asmi2_addr_adaption_asmi_mem_writedata),     //           .writedata
		.asmi_mem_byteenable   (asmi2_addr_adaption_asmi_mem_byteenable),    //           .byteenable
		.asmi_mem_burstcount   (asmi2_addr_adaption_asmi_mem_burstcount),    //           .burstcount
		.asmi_mem_waitrequest  (asmi2_addr_adaption_asmi_mem_waitrequest),   //           .waitrequest
		.asmi_mem_rddata_valid (asmi2_addr_adaption_asmi_mem_readdatavalid)  //           .readdatavalid
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
